import '@/styles/globals.css';
import Image from 'next/image';
import Link from 'next/link';

import styles from './layout.module.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='ja'>
      <body>
        <header className={styles.header}>
          <Link href='/'>
            <Image src='/logo.svg' alt='SIMPLE' className={styles.logo} width={348} height={133} priority />
          </Link>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>
          <p className={styles.cr}>© SIMPLE. All Rights Reserved 2023</p>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
